include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart;zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset
    snippet: zmk-usb-logging
    